package com.example.kyc_system.service.impl;

import com.example.kyc_system.dto.KycMonthlyReportDTO;
import com.example.kyc_system.dto.KycReportDataDTO;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("KycReportPdfServiceImpl Unit Tests")
class KycReportPdfServiceImplTest {

    @InjectMocks
    private KycReportPdfServiceImpl pdfService;

    @Test
    @DisplayName("Should generate a valid PDF byte array from report data")
    void generateReportPdf_WithValidData_ReturnsByteArray() {
        // Arrange
        KycMonthlyReportDTO report = KycMonthlyReportDTO.builder()
                .dateFrom(LocalDate.of(2023, 1, 1))
                .dateTo(LocalDate.of(2023, 1, 31))
                .totalRequests(100L)
                .verified(70L)
                .failed(20L)
                .pending(10L)
                .passRate(70.0)
                .breakdownByDocumentType(Map.of("PAN", 60L, "AADHAAR", 40L))
                .newUsersRegistered(15L)
                .totalActiveUsers(150L)
                .kycData(List.of(
                        KycReportDataDTO.builder()
                                .userId(1L)
                                .userName("Jane Doe")
                                .status("VERIFIED")
                                .documentType("PAN")
                                .attemptNumber(1)
                                .build(),
                        KycReportDataDTO.builder()
                                .userId(2L)
                                .userName("John Smith")
                                .status("FAILED")
                                .documentType("AADHAAR")
                                .attemptNumber(2)
                                .decisionReason("Blurry Image")
                                .build()))
                .build();

        // Act
        byte[] pdfBytes = pdfService.generateReportPdf(report);

        // Assert
        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0, "PDF byte array should not be empty");

        // PDF headers usually start with %PDF-
        String pdfHeader = new String(pdfBytes, 0, 5);
        assertEquals("%PDF-", pdfHeader, "Generated byte array should be a PDF document");
    }

    @Test
    @DisplayName("Should handle empty lists without failure")
    void generateReportPdf_WithEmptyData_ReturnsByteArray() {
        // Arrange
        KycMonthlyReportDTO report = KycMonthlyReportDTO.builder()
                .dateFrom(LocalDate.of(2023, 2, 1))
                .dateTo(LocalDate.of(2023, 2, 28))
                .totalRequests(0L)
                .verified(0L)
                .failed(0L)
                .pending(0L)
                .passRate(0.0)
                .breakdownByDocumentType(Map.of())
                .newUsersRegistered(0L)
                .totalActiveUsers(150L)
                .kycData(List.of())
                .build();

        // Act
        byte[] pdfBytes = pdfService.generateReportPdf(report);

        // Assert
        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0);
        String pdfHeader = new String(pdfBytes, 0, 5);
        assertEquals("%PDF-", pdfHeader);
    }
}
