package com.example.kyc_system.service.impl;

import java.time.format.TextStyle;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import com.example.kyc_system.dto.KycMonthlyReportDTO;

import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

// service/impl/KycReportEmailServiceImpl.java
@Service
@RequiredArgsConstructor
@Slf4j
public class KycReportEmailServiceImpl {

    private final JavaMailSender mailSender;

    @Value("${kyc.report.recipients}") // comma-separated emails
    private String recipients;

    @Value("${spring.mail.username}")
    private String senderEmail;

    @Async
    public void sendMonthlyReport(KycMonthlyReportDTO report) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(senderEmail);
            helper.setTo(recipients.split(","));
            helper.setSubject(String.format("📊 KYC Monthly Report - %s %d",
                    report.getReportMonth().getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH),
                    report.getReportMonth().getYear()));
            helper.setText(buildHtmlBody(report), true); // true = isHtml

            mailSender.send(message);
            log.info("Monthly KYC report sent successfully for {}", report.getReportMonth());

        } catch (Exception e) {
            log.error("Failed to send monthly KYC report: {}", e.getMessage(), e);
        }
    }

    private String buildHtmlBody(KycMonthlyReportDTO r) {
        String month = r.getReportMonth().getMonth()
                .getDisplayName(TextStyle.FULL, Locale.ENGLISH)
                + " " + r.getReportMonth().getYear();

        StringBuilder docRows = new StringBuilder();
        r.getBreakdownByDocumentType().forEach((type, count) -> docRows.append(String.format("""
                    <tr>
                      <td style="padding:8px 12px; border-bottom:1px solid #eee;">%s</td>
                      <td style="padding:8px 12px; border-bottom:1px solid #eee; text-align:center;">%d</td>
                    </tr>
                """, type, count)));

        return String.format("""
                <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto;">
                  <div style="background:#1a73e8;padding:24px;border-radius:8px 8px 0 0;">
                    <h1 style="color:#fff;margin:0;font-size:22px;">📊 KYC Monthly Report</h1>
                    <p style="color:#cce5ff;margin:4px 0 0;">%s</p>
                  </div>

                  <div style="background:#f9f9f9;padding:24px;">

                    <!-- Summary Cards -->
                    <div style="display:flex;gap:12px;margin-bottom:24px;">
                      %s %s %s %s
                    </div>

                    <!-- Pass Rate -->
                    <div style="background:#fff;border-radius:6px;padding:16px;margin-bottom:20px;
                                border-left:4px solid #1a73e8;">
                      <strong>Pass Rate:</strong>
                      <span style="font-size:24px;color:#1a73e8;margin-left:8px;">%.1f%%</span>
                    </div>

                    <!-- Document Breakdown -->
                    <h3 style="margin-bottom:8px;">Breakdown by Document Type</h3>
                    <table style="width:100%%;border-collapse:collapse;background:#fff;border-radius:6px;">
                      <thead>
                        <tr style="background:#e8f0fe;">
                          <th style="padding:10px 12px;text-align:left;">Document Type</th>
                          <th style="padding:10px 12px;text-align:center;">Count</th>
                        </tr>
                      </thead>
                      <tbody>%s</tbody>
                    </table>

                    <!-- User Stats -->
                    <div style="background:#fff;border-radius:6px;padding:16px;margin-top:20px;">
                      <strong>User Statistics</strong><br/>
                      New Registrations: <b>%d</b> &nbsp;|&nbsp; Total Active Users: <b>%d</b>
                    </div>

                    <p style="color:#999;font-size:12px;margin-top:24px;">
                      This is an automated report generated by the KYC System.
                    </p>
                  </div>
                </body></html>
                """,
                month,
                summaryCard("Total", String.valueOf(r.getTotalRequests()), "#1a73e8"),
                summaryCard("✅ Passed", String.valueOf(r.getVerified()), "#34a853"),
                summaryCard("❌ Failed", String.valueOf(r.getFailed()), "#ea4335"),
                summaryCard("⏳ Pending", String.valueOf(r.getPending()), "#fbbc04"),
                r.getPassRate(),
                docRows,
                r.getNewUsersRegistered(),
                r.getTotalActiveUsers());
    }

    private String summaryCard(String label, String value, String color) {
        return String.format("""
                    <div style="flex:1;background:#fff;border-radius:6px;padding:16px;
                                text-align:center;border-top:3px solid %s;">
                      <div style="font-size:28px;font-weight:bold;color:%s;">%s</div>
                      <div style="font-size:13px;color:#666;margin-top:4px;">%s</div>
                    </div>
                """, color, color, value, label);
    }
}
